chore(ENV-3432): Removed aws access-related variables to use injected credentials
techvelocity/velocity-blueprints pull request #9
Opened 2022-07-13 16:00 UTC by shakedembovelocity

## Description
This PR addresses ENV-3432

Currently, after 'injected credentials feature' had been deployed, the use of straight-forward access keys is redundant and even problematic.
Therefore, those access key variables had been removed in this activity.

2022-07-13 16:00 UTC, shakedembovelocity commented
Current dependencies on/for this PR:
* main
  * **PR #9** <a href="https://app.graphite.dev/github/pr/techvelocity/velocity-blueprints/9" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/techvelocity/velocity-blueprints/9?utm_source=stack-comment).

2022-07-13 18:44 UTC, yarelm requested changes
Nice! ⭐ 

Please also edit the README files for any relevant info. (There is a bullet there in `aws/sample-helm`

Another thing to complete here is the docs change, should be a small change - Menni can help with that.

I won't be able to give u the final approve because I'm PTO tomorrow, but please go over my comments, and if addressed someone else can approve. Thanks! 👍

2022-07-13 18:44 UTC, yarelm commented on getting-started/aws/sample-helm/values-velocity.yaml
> +bucket_name: 'velocity-{velocity.v1.generate:random([a-z]{1,64})}-{velocity.v1.envName}-my-bucket'
I think we should include the full template solution when ready instead of this, WDYT?

2022-07-20 10:04 UTC, orensham approved these changes

2022-07-20 13:14 UTC, merged